
---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  remote.services:
    '[API_BUSINESS_PARTNER]':
      type: "odata-v2"
      http:
        headers:
          APIKey: "nOjOcprFd0SYT6vRfQ8mRysxjlb9JVoV" # Place API Key from SAP API Business Hub here or use environment variable CDS_REMOTE_SERVICES_API_BUSINESS_PARTNER_HTTP_HEADERS_APIKEY
      destination:
        properties:
          url: "https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap"
  data-source.auto-config.enabled: false
  security:
    mock:
      users:
        - name: klaus
          password: pass_klaus
          additional:
            firstName: Klaus
            lastName: Sussard
            email: Klaus.Sussard@mail.com
        - name: mia
          password: pass_mia
          additional:
            firstName: Mia
            lastName: Bonnellac
            email: Mia.Bonnellac@mail.com
        - name: sabine
          password: pass_sabine
          roles:
            - Administrators
          additional:
            firstName: Sabine
            lastName: Autumnpike
            email: Sabine.Autumnpike@mail.com
s4:
  apikey: "nOjOcprFd0SYT6vRfQ8mRysxjlb9JVoV"